theme: minima

# Site settings
title:       Felipe Farias
author:      Felipe Farias
email:       ''
description: 'Software, Systems and Thinking.'
#baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://epilefarias.github.io' # The base hostname & protocol for your site
github:      'https://github.com/epilefarias'
instagram:   'https://instagram.com/epil3s'
facebook:    ''
linkedin:    'https://www.linkedin.com/in/epilefarias/'
